config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: 'pins#index'
    resources :boards do
    resources :pins
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
    has_many :pins
    belongs_to :users
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :board
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :boards
         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    if current_user
    @pin = current_user.pin
  else
    @pin = Pin.all
  end
end

  def new
    # @pin = Pin.find(params[:user_id])
    @pin = Pin.new
  end
  def create
    @pin = Pin.find(params[:user_id])
    @pin = @pin.create!(pin_params)
    redirect_to pin_path(@pin)
  end
  def edit
    @pin = Pin.find(params[:user_id])
  end
  def update
    @pin = Pin.find(params[:user_id])
    @pin.update(comment_params)
    redirect_to pin_path(@pin)
  end
  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy
    redirect_to pin_path(@pin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinspiration</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section>
  <% if current_user %>
    <h3><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></h3>
  <% else %>
    <h3><%= link_to 'Signup', new_user_registration_path %></h3>
    <h3><%= link_to 'Login', new_user_session_path %></h3>
  <% end %>
</section>
<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= image_tag(@user.image_url) if @user.image? %>
  <%= f.submit %>
<% end %>

app/views/pins/form.html.erb
<%= form_for @pin do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= image_tag(@user.avatar_url) if @user.avatar? %>
  <%= f.submit %>
<% end %>

app/views/pins/index.html.erb
<h1>Welcome to Pinspiration</h1>
<%= link_to "Create New Pin!", new_board_pin_path(@pins) %>
<section>
  <% @pins.each do |post| %>
    <article>
      <h2><%= link_to pin.title, pin_path(pin) %></h2>
      <time>Updated <%= pin.updated_at %></time>
      <p><%= pin.description %></p>
    </article>
  <% end %>
</section>

app/views/pins/new.html.erb
<h2>New Pin</h2>
<%= render "form" %>